/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarrierSetupRouteImport } from './routes/carrier-setup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCarrierSetupRouteImport } from './routes/api/public/carrier-setup'
import { Route as ApiPublicHooksPagespeedRouteImport } from './routes/api/public/hooks/pagespeed'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrierSetupRoute = CarrierSetupRouteImport.update({
  id: '/carrier-setup',
  path: '/carrier-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCarrierSetupRoute = ApiPublicCarrierSetupRouteImport.update({
  id: '/api/public/carrier-setup',
  path: '/api/public/carrier-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPagespeedRoute = ApiPublicHooksPagespeedRouteImport.update({
  id: '/api/public/hooks/pagespeed',
  path: '/api/public/hooks/pagespeed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carrier-setup': typeof CarrierSetupRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/carrier-setup': typeof ApiPublicCarrierSetupRoute
  '/api/public/hooks/pagespeed': typeof ApiPublicHooksPagespeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carrier-setup': typeof CarrierSetupRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/carrier-setup': typeof ApiPublicCarrierSetupRoute
  '/api/public/hooks/pagespeed': typeof ApiPublicHooksPagespeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carrier-setup': typeof CarrierSetupRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/carrier-setup': typeof ApiPublicCarrierSetupRoute
  '/api/public/hooks/pagespeed': typeof ApiPublicHooksPagespeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/carrier-setup'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/api/public/carrier-setup'
    | '/api/public/hooks/pagespeed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/carrier-setup'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/api/public/carrier-setup'
    | '/api/public/hooks/pagespeed'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/carrier-setup'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/api/public/carrier-setup'
    | '/api/public/hooks/pagespeed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CarrierSetupRoute: typeof CarrierSetupRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCarrierSetupRoute: typeof ApiPublicCarrierSetupRoute
  ApiPublicHooksPagespeedRoute: typeof ApiPublicHooksPagespeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrier-setup': {
      id: '/carrier-setup'
      path: '/carrier-setup'
      fullPath: '/carrier-setup'
      preLoaderRoute: typeof CarrierSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/carrier-setup': {
      id: '/api/public/carrier-setup'
      path: '/api/public/carrier-setup'
      fullPath: '/api/public/carrier-setup'
      preLoaderRoute: typeof ApiPublicCarrierSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pagespeed': {
      id: '/api/public/hooks/pagespeed'
      path: '/api/public/hooks/pagespeed'
      fullPath: '/api/public/hooks/pagespeed'
      preLoaderRoute: typeof ApiPublicHooksPagespeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CarrierSetupRoute: CarrierSetupRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCarrierSetupRoute: ApiPublicCarrierSetupRoute,
  ApiPublicHooksPagespeedRoute: ApiPublicHooksPagespeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
