/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TruckDispatchHoustonRouteImport } from './routes/truck-dispatch-houston'
import { Route as TruckDispatchDallasRouteImport } from './routes/truck-dispatch-dallas'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StepDeckDispatchRouteImport } from './routes/step-deck-dispatch'
import { Route as SmallFleetDispatchRouteImport } from './routes/small-fleet-dispatch'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReeferDispatchRouteImport } from './routes/reefer-dispatch'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PowerOnlyDispatchRouteImport } from './routes/power-only-dispatch'
import { Route as OwnerOperatorDispatchRouteImport } from './routes/owner-operator-dispatch'
import { Route as HotshotDispatchRouteImport } from './routes/hotshot-dispatch'
import { Route as FlatbedDispatchRouteImport } from './routes/flatbed-dispatch'
import { Route as DryVanDispatchRouteImport } from './routes/dry-van-dispatch'
import { Route as DedicatedDispatcherRouteImport } from './routes/dedicated-dispatcher'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarrierSetupRouteImport } from './routes/carrier-setup'
import { Route as BoxTruckDispatchRouteImport } from './routes/box-truck-dispatch'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicCarrierSetupRouteImport } from './routes/api/public/carrier-setup'
import { Route as ApiPublicHooksPagespeedRouteImport } from './routes/api/public/hooks/pagespeed'

const TruckDispatchHoustonRoute = TruckDispatchHoustonRouteImport.update({
  id: '/truck-dispatch-houston',
  path: '/truck-dispatch-houston',
  getParentRoute: () => rootRouteImport,
} as any)
const TruckDispatchDallasRoute = TruckDispatchDallasRouteImport.update({
  id: '/truck-dispatch-dallas',
  path: '/truck-dispatch-dallas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StepDeckDispatchRoute = StepDeckDispatchRouteImport.update({
  id: '/step-deck-dispatch',
  path: '/step-deck-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const SmallFleetDispatchRoute = SmallFleetDispatchRouteImport.update({
  id: '/small-fleet-dispatch',
  path: '/small-fleet-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReeferDispatchRoute = ReeferDispatchRouteImport.update({
  id: '/reefer-dispatch',
  path: '/reefer-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerOnlyDispatchRoute = PowerOnlyDispatchRouteImport.update({
  id: '/power-only-dispatch',
  path: '/power-only-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOperatorDispatchRoute = OwnerOperatorDispatchRouteImport.update({
  id: '/owner-operator-dispatch',
  path: '/owner-operator-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const HotshotDispatchRoute = HotshotDispatchRouteImport.update({
  id: '/hotshot-dispatch',
  path: '/hotshot-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatbedDispatchRoute = FlatbedDispatchRouteImport.update({
  id: '/flatbed-dispatch',
  path: '/flatbed-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DryVanDispatchRoute = DryVanDispatchRouteImport.update({
  id: '/dry-van-dispatch',
  path: '/dry-van-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DedicatedDispatcherRoute = DedicatedDispatcherRouteImport.update({
  id: '/dedicated-dispatcher',
  path: '/dedicated-dispatcher',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrierSetupRoute = CarrierSetupRouteImport.update({
  id: '/carrier-setup',
  path: '/carrier-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxTruckDispatchRoute = BoxTruckDispatchRouteImport.update({
  id: '/box-truck-dispatch',
  path: '/box-truck-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCarrierSetupRoute = ApiPublicCarrierSetupRouteImport.update({
  id: '/api/public/carrier-setup',
  path: '/api/public/carrier-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPagespeedRoute = ApiPublicHooksPagespeedRouteImport.update({
  id: '/api/public/hooks/pagespeed',
  path: '/api/public/hooks/pagespeed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/box-truck-dispatch': typeof BoxTruckDispatchRoute
  '/carrier-setup': typeof CarrierSetupRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dedicated-dispatcher': typeof DedicatedDispatcherRoute
  '/dry-van-dispatch': typeof DryVanDispatchRoute
  '/flatbed-dispatch': typeof FlatbedDispatchRoute
  '/hotshot-dispatch': typeof HotshotDispatchRoute
  '/owner-operator-dispatch': typeof OwnerOperatorDispatchRoute
  '/power-only-dispatch': typeof PowerOnlyDispatchRoute
  '/privacy': typeof PrivacyRoute
  '/reefer-dispatch': typeof ReeferDispatchRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-fleet-dispatch': typeof SmallFleetDispatchRoute
  '/step-deck-dispatch': typeof StepDeckDispatchRoute
  '/terms': typeof TermsRoute
  '/truck-dispatch-dallas': typeof TruckDispatchDallasRoute
  '/truck-dispatch-houston': typeof TruckDispatchHoustonRoute
  '/api/public/carrier-setup': typeof ApiPublicCarrierSetupRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/hooks/pagespeed': typeof ApiPublicHooksPagespeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/box-truck-dispatch': typeof BoxTruckDispatchRoute
  '/carrier-setup': typeof CarrierSetupRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dedicated-dispatcher': typeof DedicatedDispatcherRoute
  '/dry-van-dispatch': typeof DryVanDispatchRoute
  '/flatbed-dispatch': typeof FlatbedDispatchRoute
  '/hotshot-dispatch': typeof HotshotDispatchRoute
  '/owner-operator-dispatch': typeof OwnerOperatorDispatchRoute
  '/power-only-dispatch': typeof PowerOnlyDispatchRoute
  '/privacy': typeof PrivacyRoute
  '/reefer-dispatch': typeof ReeferDispatchRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-fleet-dispatch': typeof SmallFleetDispatchRoute
  '/step-deck-dispatch': typeof StepDeckDispatchRoute
  '/terms': typeof TermsRoute
  '/truck-dispatch-dallas': typeof TruckDispatchDallasRoute
  '/truck-dispatch-houston': typeof TruckDispatchHoustonRoute
  '/api/public/carrier-setup': typeof ApiPublicCarrierSetupRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/hooks/pagespeed': typeof ApiPublicHooksPagespeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/box-truck-dispatch': typeof BoxTruckDispatchRoute
  '/carrier-setup': typeof CarrierSetupRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dedicated-dispatcher': typeof DedicatedDispatcherRoute
  '/dry-van-dispatch': typeof DryVanDispatchRoute
  '/flatbed-dispatch': typeof FlatbedDispatchRoute
  '/hotshot-dispatch': typeof HotshotDispatchRoute
  '/owner-operator-dispatch': typeof OwnerOperatorDispatchRoute
  '/power-only-dispatch': typeof PowerOnlyDispatchRoute
  '/privacy': typeof PrivacyRoute
  '/reefer-dispatch': typeof ReeferDispatchRoute
  '/services': typeof ServicesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-fleet-dispatch': typeof SmallFleetDispatchRoute
  '/step-deck-dispatch': typeof StepDeckDispatchRoute
  '/terms': typeof TermsRoute
  '/truck-dispatch-dallas': typeof TruckDispatchDallasRoute
  '/truck-dispatch-houston': typeof TruckDispatchHoustonRoute
  '/api/public/carrier-setup': typeof ApiPublicCarrierSetupRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/hooks/pagespeed': typeof ApiPublicHooksPagespeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/box-truck-dispatch'
    | '/carrier-setup'
    | '/contact'
    | '/cookies'
    | '/dedicated-dispatcher'
    | '/dry-van-dispatch'
    | '/flatbed-dispatch'
    | '/hotshot-dispatch'
    | '/owner-operator-dispatch'
    | '/power-only-dispatch'
    | '/privacy'
    | '/reefer-dispatch'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/small-fleet-dispatch'
    | '/step-deck-dispatch'
    | '/terms'
    | '/truck-dispatch-dallas'
    | '/truck-dispatch-houston'
    | '/api/public/carrier-setup'
    | '/api/public/chat'
    | '/api/public/contact'
    | '/api/public/hooks/pagespeed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/box-truck-dispatch'
    | '/carrier-setup'
    | '/contact'
    | '/cookies'
    | '/dedicated-dispatcher'
    | '/dry-van-dispatch'
    | '/flatbed-dispatch'
    | '/hotshot-dispatch'
    | '/owner-operator-dispatch'
    | '/power-only-dispatch'
    | '/privacy'
    | '/reefer-dispatch'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/small-fleet-dispatch'
    | '/step-deck-dispatch'
    | '/terms'
    | '/truck-dispatch-dallas'
    | '/truck-dispatch-houston'
    | '/api/public/carrier-setup'
    | '/api/public/chat'
    | '/api/public/contact'
    | '/api/public/hooks/pagespeed'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/box-truck-dispatch'
    | '/carrier-setup'
    | '/contact'
    | '/cookies'
    | '/dedicated-dispatcher'
    | '/dry-van-dispatch'
    | '/flatbed-dispatch'
    | '/hotshot-dispatch'
    | '/owner-operator-dispatch'
    | '/power-only-dispatch'
    | '/privacy'
    | '/reefer-dispatch'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/small-fleet-dispatch'
    | '/step-deck-dispatch'
    | '/terms'
    | '/truck-dispatch-dallas'
    | '/truck-dispatch-houston'
    | '/api/public/carrier-setup'
    | '/api/public/chat'
    | '/api/public/contact'
    | '/api/public/hooks/pagespeed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoxTruckDispatchRoute: typeof BoxTruckDispatchRoute
  CarrierSetupRoute: typeof CarrierSetupRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DedicatedDispatcherRoute: typeof DedicatedDispatcherRoute
  DryVanDispatchRoute: typeof DryVanDispatchRoute
  FlatbedDispatchRoute: typeof FlatbedDispatchRoute
  HotshotDispatchRoute: typeof HotshotDispatchRoute
  OwnerOperatorDispatchRoute: typeof OwnerOperatorDispatchRoute
  PowerOnlyDispatchRoute: typeof PowerOnlyDispatchRoute
  PrivacyRoute: typeof PrivacyRoute
  ReeferDispatchRoute: typeof ReeferDispatchRoute
  ServicesRoute: typeof ServicesRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmallFleetDispatchRoute: typeof SmallFleetDispatchRoute
  StepDeckDispatchRoute: typeof StepDeckDispatchRoute
  TermsRoute: typeof TermsRoute
  TruckDispatchDallasRoute: typeof TruckDispatchDallasRoute
  TruckDispatchHoustonRoute: typeof TruckDispatchHoustonRoute
  ApiPublicCarrierSetupRoute: typeof ApiPublicCarrierSetupRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicHooksPagespeedRoute: typeof ApiPublicHooksPagespeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/truck-dispatch-houston': {
      id: '/truck-dispatch-houston'
      path: '/truck-dispatch-houston'
      fullPath: '/truck-dispatch-houston'
      preLoaderRoute: typeof TruckDispatchHoustonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truck-dispatch-dallas': {
      id: '/truck-dispatch-dallas'
      path: '/truck-dispatch-dallas'
      fullPath: '/truck-dispatch-dallas'
      preLoaderRoute: typeof TruckDispatchDallasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-deck-dispatch': {
      id: '/step-deck-dispatch'
      path: '/step-deck-dispatch'
      fullPath: '/step-deck-dispatch'
      preLoaderRoute: typeof StepDeckDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/small-fleet-dispatch': {
      id: '/small-fleet-dispatch'
      path: '/small-fleet-dispatch'
      fullPath: '/small-fleet-dispatch'
      preLoaderRoute: typeof SmallFleetDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reefer-dispatch': {
      id: '/reefer-dispatch'
      path: '/reefer-dispatch'
      fullPath: '/reefer-dispatch'
      preLoaderRoute: typeof ReeferDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-only-dispatch': {
      id: '/power-only-dispatch'
      path: '/power-only-dispatch'
      fullPath: '/power-only-dispatch'
      preLoaderRoute: typeof PowerOnlyDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-operator-dispatch': {
      id: '/owner-operator-dispatch'
      path: '/owner-operator-dispatch'
      fullPath: '/owner-operator-dispatch'
      preLoaderRoute: typeof OwnerOperatorDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotshot-dispatch': {
      id: '/hotshot-dispatch'
      path: '/hotshot-dispatch'
      fullPath: '/hotshot-dispatch'
      preLoaderRoute: typeof HotshotDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flatbed-dispatch': {
      id: '/flatbed-dispatch'
      path: '/flatbed-dispatch'
      fullPath: '/flatbed-dispatch'
      preLoaderRoute: typeof FlatbedDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dry-van-dispatch': {
      id: '/dry-van-dispatch'
      path: '/dry-van-dispatch'
      fullPath: '/dry-van-dispatch'
      preLoaderRoute: typeof DryVanDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dedicated-dispatcher': {
      id: '/dedicated-dispatcher'
      path: '/dedicated-dispatcher'
      fullPath: '/dedicated-dispatcher'
      preLoaderRoute: typeof DedicatedDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrier-setup': {
      id: '/carrier-setup'
      path: '/carrier-setup'
      fullPath: '/carrier-setup'
      preLoaderRoute: typeof CarrierSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-truck-dispatch': {
      id: '/box-truck-dispatch'
      path: '/box-truck-dispatch'
      fullPath: '/box-truck-dispatch'
      preLoaderRoute: typeof BoxTruckDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/carrier-setup': {
      id: '/api/public/carrier-setup'
      path: '/api/public/carrier-setup'
      fullPath: '/api/public/carrier-setup'
      preLoaderRoute: typeof ApiPublicCarrierSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pagespeed': {
      id: '/api/public/hooks/pagespeed'
      path: '/api/public/hooks/pagespeed'
      fullPath: '/api/public/hooks/pagespeed'
      preLoaderRoute: typeof ApiPublicHooksPagespeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoxTruckDispatchRoute: BoxTruckDispatchRoute,
  CarrierSetupRoute: CarrierSetupRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DedicatedDispatcherRoute: DedicatedDispatcherRoute,
  DryVanDispatchRoute: DryVanDispatchRoute,
  FlatbedDispatchRoute: FlatbedDispatchRoute,
  HotshotDispatchRoute: HotshotDispatchRoute,
  OwnerOperatorDispatchRoute: OwnerOperatorDispatchRoute,
  PowerOnlyDispatchRoute: PowerOnlyDispatchRoute,
  PrivacyRoute: PrivacyRoute,
  ReeferDispatchRoute: ReeferDispatchRoute,
  ServicesRoute: ServicesRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmallFleetDispatchRoute: SmallFleetDispatchRoute,
  StepDeckDispatchRoute: StepDeckDispatchRoute,
  TermsRoute: TermsRoute,
  TruckDispatchDallasRoute: TruckDispatchDallasRoute,
  TruckDispatchHoustonRoute: TruckDispatchHoustonRoute,
  ApiPublicCarrierSetupRoute: ApiPublicCarrierSetupRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicHooksPagespeedRoute: ApiPublicHooksPagespeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
